# Generated by Django 5.1.6 on 2025-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_address_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
