# Generated by Django 5.1.6 on 2025-03-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_address_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_area',
            new_name='area',
        ),
    ]
