# Generated by Django 5.1.6 on 2025-03-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_address_area_address_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='area',
            new_name='Address',
        ),
    ]
