# Generated by Django 5.1.6 on 2025-03-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_area_address_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AddField(
            model_name='user',
            name='gstin',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
