# Generated by Django 5.1.6 on 2025-03-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_options_alter_address_name'),
        ('vendor', '0006_vendorprofile_admin_vendorprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorprofile'),
        ),
    ]
