# Generated by Django 5.1.6 on 2025-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_address_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
