# Generated by Django 5.1.6 on 2025-04-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_gstin_remove_user_store_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
