# Generated by Django 5.1.6 on 2025-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_address_address_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
