# Generated by Django 5.0.3 on 2025-04-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_address_address_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
    ]
