# Generated by Django 5.1.6 on 2025-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed dependency on ('users', '0001_initial') to fix migration ordering issues.
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('password_confirmation', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
