# Generated by Django 5.1.6 on 2025-02-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
