# Generated by Django 5.1.6 on 2025-03-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner_brand_category_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
