# Generated by Django 5.1.6 on 2025-03-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
