# Generated by Django 5.1.6 on 2025-03-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_description_alter_product_image'),
        ('product', '0026_product_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
