# Generated by Django 5.1.6 on 2025-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
