# Generated by Django 5.1.6 on 2025-02-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
