# Generated by Django 5.1.6 on 2025-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_to_bag',
            field=models.BooleanField(default=False),
        ),
    ]
