# Generated by Django 5.1.6 on 2025-03-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cart_confirmation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
