# Generated by Django 5.1.6 on 2025-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_order_confirmation_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='exit', max_length=200, upload_to='product/'),
            preserve_default=False,
        ),
    ]
