# Generated by Django 5.1.6 on 2025-03-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_initial'),
        ('product', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='core.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
