# Generated by Django 5.1.6 on 2025-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_cart_image_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='products/default_image.jpg', upload_to=''),
        ),
    ]
