# Generated by Django 5.1.6 on 2025-03-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_description_alter_product_image'),
        ('product', '0020_alter_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='CartItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='product/default_image.jpg', upload_to=''),
        ),
    ]
