# Generated by Django 5.1.6 on 2025-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_cart_cartitem_alter_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CartItem',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
