# Generated by Django 5.1.6 on 2025-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_product_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
