# Generated by Django 5.1.6 on 2025-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_image_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='xyz',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/'),
        ),
    ]
