# Generated by Django 5.1.6 on 2025-03-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_image_image_image_xyz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='xyz',
            new_name='image',
        ),
    ]
