# Generated by Django 5.1.6 on 2025-03-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_product_category_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
