# Generated by Django 5.1.6 on 2025-03-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_remove_category_description_remove_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
