# Generated by Django 5.1.6 on 2025-03-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_remove_category_product_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
