# Generated by Django 5.1.6 on 2025-03-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_category_description_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
