# Generated by Django 5.1.6 on 2025-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
