# Generated by Django 5.1.6 on 2025-03-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
