# Generated by Django 5.1.6 on 2025-03-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_brand_product_brand'),
        ('vendor', '0011_delete_vendor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorprofile'),
        ),
    ]
