# Generated by Django 5.1.6 on 2025-04-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_order_options_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
