# Generated by Django 5.1.6 on 2025-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
