# Generated by Django 5.1.6 on 2025-04-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
