# Generated by Django 5.1.6 on 2025-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_remove_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
