# Generated by Django 5.1.6 on 2025-04-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_items_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
