# Generated by Django 5.1.6 on 2025-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
